### ISSUE TITLE
Claimsettings menu deleting items

### ISSUE THREAD

**Issue by RJD111** [WhipDevelopment/CrashClaim#15] opened 2022-01-24 20:59 UTC
When in the claimsettings menu, although you cannot click and move items in your inventory, you can hover over an empty slot in the claimsettings inventory and press a number on your keyboard that corresponds to a hotbar slot therefore moving the item(s) into the menu inventory. Doing this will mean you permanently lose the item

**Comment by DaJokni** [comment] 2023-05-27 11:56
i can repoduce this issue

https://github.com/WhipDevelopment/CrashClaim/assets/56400974/d8f0aa1b-a83d-4d88-86cf-ce84a73d0b4d

**Comment by SenPr** [comment] 2023-05-27 14:09
This is a bug caused by CrashUtils (library used by CrashClaims)

**Comment by SenPr** [comment] 2023-05-27 14:40
So I think I have a fix. The fix I tried is relatively simple, but not 100% tested. This requires you to compile both CrashUtils and CrashClaim by yourself if you want to patch this.
You can find CrashUtils here: https://github.com/CrashCraftNetwork/CrashUtils

In CrashMenuController.java, delete or comment line 20 and 21 which are:
`if (e.getCurrentItem().get == null)
            return;`
Since the slot is null it return the function so nothing else get processed, making the event going through instead of being cancelled. It is only when the slot isn't null that it gets processed properly. Not sure why these was added, guessing it was for optimization?

**Comment by DaJokni** [comment] 2023-05-27 14:41
i do wonder why crashutils exists seperately, wonder if bundling it into the plugin would be an issue

**Comment by DaJokni** [comment] 2024-02-01 21:18
this was fixed by #37

**Closed as completed** 2024-05-26 15:00 UTC
